pages/index.en-US.mdx
pages/index.zh-CN.mdx
pages/index.zh-TW.mdx

add og image meta for introduction

---

pages/guides/nodejs/nestjs.en-US.mdx
pages/guides/nodejs/nestjs.zh-CN.mdx
pages/guides/nodejs/nestjs.zh-TW.mdx
pages/index.en-US.mdx
pages/index.zh-CN.mdx
pages/index.zh-TW.mdx

- [Add `nestjs.zh-TW.mdx`.](https://github.com/zeabur/docs/commit/9e73f2b1786c5f31415ee9bd0a602f2290c2357d)
- [Add `nestjs.zh-CN.mdx` and `nestjs.en-US.mdx`.](https://github.com/zeabur/docs/commit/f3d96d490ed2b1232d80f267db2607f706b41b8b)
- [Fix typo.](https://github.com/zeabur/docs/commit/8e9d8af08b7b4bb84dbfcf79864ea41c4e25c48b)

Add NestJS doc.

---

pages/guides/php/laravel.zh-TW.mdx

Fix `laravel.zh-TW.mdx` code blocks syntax.
[Reproduction](https://zeabur-docs-liohhcikp-chia1104.vercel.app/zh-TW/guides/php/laravel)

Fix `laravel.zh-TW.mdx` code blocks syntax.

---

theme.config.js

`https://zeabur.com/home` is broken with 404

fix: fix the home link

---

pages/get-started.zh-TW.mdx

docs: change environment variables link to zh-tw

docs: update `get-started.zh-TW.mdx` link

---

pages/deploy/domain-binding.en-US.mdx
pages/deploy/domain-binding.zh-CN.mdx
pages/deploy/domain-binding.zh-TW.mdx

- add please turn off Cloudflare's proxy

fix(domain binding): proxy status

---

marketplace/rsshub.json

add rsshub support

---

marketplace/halo.json

Added [Halo](https://github.com/halo-dev/halo) to Marketplace list.
By the way, do I need to test? Currently I don't know how to make usage tests, Thanks.

Add Halo to marketplace

---

marketplace/opencatd-open.json

add opencatd-open

---

marketplace/sqlchat.json

[SQL Chat](https://github.com/sqlchat/sqlchat) is Chat-based SQL Client.

Add SQL Chat to marketplace

---

marketplace/bytebase.json

[Bytebase](https://github.com/bytebase/bytebase) is Database CI/CD for DevOps teams. 
🤔 But I can be sure whether can run fine in zeabur. because without some param compared to the official documentation.

add bytebase to marketplace

---

marketplace/vaultwarden.json

I hope Vaultwarden meets the requirements for deployment on Zeabur : )

docs: add `vaultwarden.json` to marketplace

---

marketplace/sqlchat.json

upstream docker update. 👀
[chore: update doc to make DATABASE_URL required · sqlchat/sqlchat@cfbdf5c](https://github.com/sqlchat/sqlchat/commit/cfbdf5cced4c54a1c92e8161c43c28c3592e8278)

update Required environment variables

---

marketplace/apicat.json

Complement the apicat's image and modify the port to 8000

Complement the apicat's image and modify the port to 8000

---

docs/components/WorkingInProgress/en_US.mdx
docs/components/WorkingInProgress/index.tsx
docs/components/WorkingInProgress/mdx.d.ts
docs/components/WorkingInProgress/zh_CN.mdx
docs/components/WorkingInProgress/zh_TW.mdx
docs/pages/databases/mongodb.en-US.mdx
docs/pages/databases/mongodb.zh-TW.mdx
docs/pages/databases/redis.en-US.mdx
docs/pages/databases/redis.zh-CN.mdx
docs/pages/databases/redis.zh-TW.mdx
docs/theme.config.js

- feat: Add WorkingInProgress component
- refactor: Move all the WIP to our WIP component

ZEA-1154: Add our own `WorkingInProgrss` component

---

docs/pages/marketplace/rsshub.zh-TW.mdx

fix: fixing a typo

---

docs/pages/guides/python/django.en-US.mdx

docs: django-en document

---

marketplace/rsstt.json

[RSStT](https://github.com/Rongronggg9/RSS-to-Telegram-Bot) is a Telegram RSS bot that cares about your reading experience.

add rsstt support

---

marketplace/prometheus.json

https://prometheus.io/
prometheus is a monitoring solution🤔 I try to deploy it to monitoring my backend

add prometheus app

---

prebuilts/mongodb.toml
prebuilts/mysql.toml
prebuilts/postgresql.toml
prebuilts/redis.toml

Now only these five fields are left:
* Command for connecting from the external network
* Account
* Password
* Hostname that can be connected from the external network
* Port corresponding to the above hostname

refactor(prebuilts): Remove any useless instructions

---

prebuilts/rabbitmq.toml

RabbitMQ is a widely used open-source message broker that implements the Advanced Message Queuing Protocol (AMQP)
https://github.com/rabbitmq/rabbitmq-server
https://www.rabbitmq.com/rabbitmqctl.8.html

 feat(prebuilt): add rabbitmq:3-management

---

prebuilts/etcd.toml

due to etcd is the bedrock of cloud

Add etcd into prebuild

---

docs/pages/guides/nodejs.zh-TW.mdx

新增「額外注意事項」在 docs nodejs 的 nodejs.zh-TW.mdx
1. 修改的文件：docs/pages/guides/nodejs.zh-TW.mdx 
2. 位置：文件的最下方
2. 額外注意事項內容：使用 process.env.PORT 及 避免使用 nodemon

新增文件內容:「## 部屬nodejs時,額外注意事項」 在  docs/pages/guides/nodejs.zh-TW.mdx 最下方

---

prebuilts/focalboard.toml

https://github.com/mattermost/focalboard

feat: add Focalboard

---

prebuilts/ferretdb.toml
prebuilts/ghost.toml
prebuilts/halo.toml
prebuilts/logto.toml
prebuilts/mongodb.toml
prebuilts/mysql.toml
prebuilts/mysql5.toml
prebuilts/n8n.toml
prebuilts/postgresql.toml
prebuilts/rabbitmq.toml
prebuilts/redis.toml
prebuilts/rsshub.toml
prebuilts/schema.json
prebuilts/ttrss.toml
prebuilts/unami.toml
prebuilts/wordpress.toml

refactor(prebuilts): Rewrite documentations

---

prebuilts/artalk.toml

https://github.com/ArtalkJS/Artalk

prebuilt: add artalk

---

docs/pages/guides/deno/fresh.zh-CN.mdx

docs(zh-cn): fix typo

---

prebuilts/librechat.toml

Prebuilt for https://github.com/danny-avila/LibreChat

prebuilt: librechat

---

prebuilts/flowise.toml

https://github.com/FlowiseAI/Flowise
Flowise: Drag & drop UI to build your customized LLM flow.

prebuilt: add flowise

---

docs/pages/marketplace/rabbitmq.zh-CN.mdx
docs/pages/marketplace/rabbitmq.zh-TW.mdx

docs: fix image description bug in rabbitmq doc

---

dashboard/locales/es-ES/account.json
dashboard/locales/es-ES/auth.json
dashboard/locales/es-ES/billing.json
dashboard/locales/es-ES/common.json
dashboard/locales/es-ES/deploy.json
dashboard/locales/es-ES/deployment.json
dashboard/locales/es-ES/error.json
dashboard/locales/es-ES/header.json
dashboard/locales/es-ES/invite.json
dashboard/locales/es-ES/login.json
dashboard/locales/es-ES/modals.json
dashboard/locales/es-ES/overview.json
dashboard/locales/es-ES/pricing.json
dashboard/locales/es-ES/project-list.json
dashboard/locales/es-ES/project.json
dashboard/locales/es-ES/service.json
dashboard/locales/es-ES/settings.json
dashboard/locales/es-ES/template.json
dashboard/locales/es-ES/toast.json
dashboard/locales/es-ES/toolbar.json

Add Spanish support for dashboard. Just using AI to translate those files and we may need further improvements by native Spanish speakers cc @dreyfus92

wip: add Spanish support

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/suggestion.md

let's add some issue templates for developer.
Like this:
https://github.com/Undertone0809/promptulate This project as a reference.

add issue template

---

prebuilts/linkwarden.toml

fix: linkwarden nextauth variables

---

prebuilts/changedetection-io.toml

prebuilt: changedetection.io

---

prebuilts/apicat.toml

fix: fix icon for apicat prebuilt

---

prebuilts/schema.json

chore(prebuilts): Fix Env regex & Bump schema version

---

prebuilts/metabase.toml

feat(prebuilts): Metabase

---

prebuilts/wewe-rss.toml

reference: https://github.com/cooderl/wewe-rss/blob/main/docker-compose.sqlite.yml

prebuilt: wewew-rss

---

docs/pages/guides/python.en-US.mdx
docs/pages/guides/python.es-ES.mdx
docs/pages/guides/python.ja-JP.mdx
docs/pages/guides/python.zh-CN.mdx
docs/pages/guides/python.zh-TW.mdx

- **docs(guides/python): Add "Python version" section**
- **docs(guides/python): Translate to the latest chapter**

ZEA-3338: Add docs about how to specify Python version

---

docs/pages/guides/nodejs.en-US.mdx
docs/pages/guides/nodejs.es-ES.mdx
docs/pages/guides/nodejs.ja-JP.mdx
docs/pages/guides/nodejs.zh-CN.mdx
docs/pages/guides/nodejs.zh-TW.mdx

- **style(guides/nodejs): Adjust format**
- **docs(guides/nodejs): Add Monorepo section**
- **docs(guides/nodejs): Adjust description for some sections**
- **docs(guides/nodejs): Add environment variable settings**

ZEA-3481: Add Node.js monorepo documentation

---

docs/package.json
docs/pnpm-lock.yaml

- **chore: Update caniuse-lite**
- **chore: Add sharp**

Update caniuse-lite and Sharp

---

docs/pages/guides/php.en-US.mdx
docs/pages/guides/php.es-ES.mdx
docs/pages/guides/php.ja-JP.mdx
docs/pages/guides/php.zh-CN.mdx
docs/pages/guides/php.zh-TW.mdx

Block: https://github.com/zeabur/zbpack/pull/302

docs(guides/php): PHP build/start command

---

docs/pages/guides/python.en-US.mdx
docs/pages/guides/python.es-ES.mdx
docs/pages/guides/python.ja-JP.mdx
docs/pages/guides/python.zh-CN.mdx
docs/pages/guides/python.zh-TW.mdx

Blocks: https://github.com/zeabur/zbpack/pull/303
- **docs(guides/python): NPM & build/start command**
- **chore(guides/python): Update translation**

Add documentation for npm supports and custom build/start

---

templates/kafka/template.yaml

- **feat(template/kafka): Add localization for Kafka template**
- **refactor(template/kafka): Simplify description**

ZEA-3540: Simplify description, add localization to Kafka

---

docs/pages/guides/nodejs.en-US.mdx
docs/pages/guides/nodejs.es-ES.mdx
docs/pages/guides/nodejs.ja-JP.mdx
docs/pages/guides/nodejs.zh-CN.mdx
docs/pages/guides/nodejs.zh-TW.mdx
docs/pages/guides/python.en-US.mdx
docs/pages/guides/python.es-ES.mdx
docs/pages/guides/python.ja-JP.mdx
docs/pages/guides/python.zh-CN.mdx
docs/pages/guides/python.zh-TW.mdx

- **docs(guides): Add web scraping chapters**
- **docs(guides/python): Add translation**
- **docs(guides/nodejs): Add translation**

ZEA-3614: Web scraping document

---

schema/prebuilt.json

https://json-schema.app/view/%23%2Fdefinitions%2FSource/%23%2Fdefinitions%2FGit?url=https%3A%2F%2Fschema.zeabur.app%2Fprebuilt.json

feat(schema): rootDirectory and repoID -> repo

---

docs/.envrc
docs/.gitignore
docs/devenv.lock
docs/devenv.nix
docs/devenv.yaml
docs/pnpm-lock.yaml

- **chore: Add devenv**
- **chore: Update lockfile**

Add devenv configuration for docs

---

docs/package.json
docs/pages/_app.mdx
docs/pages/_app.tsx
docs/pnpm-lock.yaml

- **chore: Upgrade docs dependencies**
- **refactor: Rename _app.tsx to _app.mdx**

Improve Nextra performance

---

docs/pages/guides/rust.en-US.mdx
docs/pages/guides/rust.es-ES.mdx
docs/pages/guides/rust.ja-JP.mdx
docs/pages/guides/rust.zh-CN.mdx
docs/pages/guides/rust.zh-TW.mdx

- **docs(guides/rust): Correct artifact name**
- **docs(guides/rust): Correct sqlite3 command**
- **docs(guides/rust): Update translation**

ZEA-3963: Rust: correct artifact name

---

schema/prebuilt.json
schema/template.json

feat(schema/prebuilt): Update JSON schema

---

schema/prebuilt.json
schema/template.json

- **fix(schema): Mark optional properties as nullable**
- **fix(schema): Use union type instead of nullable**

ZEA-4023: Mark optional properties as nullable

---

docs/pages/template/template-in-code.en-US.mdx
docs/pages/template/template-in-code.es-ES.mdx
docs/pages/template/template-in-code.ja-JP.mdx
docs/pages/template/template-in-code.zh-CN.mdx
docs/pages/template/template-in-code.zh-TW.mdx

- **docs(template): Permission and runAsUserID**. Fixed ZEA-4004
- **docs(template): Dependencies**. Fixed ZEA-3998

Add permission, runAsUserID, dependencies docs

---

docs/middleware.ts

Add sitemap.xml to the middleware configuration to enable access to the sitemap.xml URL.

feat(docs): add sitemap.xml to middleware config

---

docs/pages/en-US/guides/python.mdx
docs/pages/es-ES/guides/python.mdx
docs/pages/ja-JP/guides/python.mdx
docs/pages/zh-CN/guides/python.mdx
docs/pages/zh-TW/guides/python.mdx

https://github.com/zeabur/zbpack/pull/385

docs(python): Add "Specifying the Package Manager" section

---

docs/pages/en-US/template/template-in-code.mdx
docs/pages/es-ES/template/template-in-code.mdx
docs/pages/ja-JP/template/template-in-code.mdx
docs/pages/zh-CN/template/template-in-code.mdx
docs/pages/zh-TW/template/template-in-code.mdx

文档有误
在制作 https://zeabur.com/templates/80HJJG 时发现的
discord link: https://discord.com/channels/1060209568820494336/1303279016731480095/1303653512286310462

fix(docs): domainKey 在 service 下才工作

---

docs/pages/en-US/guides/php.mdx
docs/pages/en-US/guides/php/laravel.mdx
docs/pages/en-US/guides/php/symfony.mdx
docs/pages/es-ES/guides/php.mdx
docs/pages/es-ES/guides/php/laravel.mdx
docs/pages/es-ES/guides/php/symfony.mdx
docs/pages/ja-JP/guides/php.mdx
docs/pages/ja-JP/guides/php/laravel.mdx
docs/pages/ja-JP/guides/php/symfony.mdx
docs/pages/zh-CN/guides/php.mdx
docs/pages/zh-CN/guides/php/laravel.mdx
docs/pages/zh-CN/guides/php/symfony.mdx
docs/pages/zh-TW/guides/php.mdx
docs/pages/zh-TW/guides/php/laravel.mdx
docs/pages/zh-TW/guides/php/symfony.mdx

- **docs: Update PHP documentation**
- **docs: Add Symfony documentation**
- **docs: Add new sections for Laravel documentation**
- **docs: Update PHP translation for ja-JP**
- **docs: Update PHP translation for es-ES**

docs: Update PHP, Laravel and Symfony documentation

---

schema/prebuilt.json
schema/template.json

```json
{
"healthCheck": {
"type": "TCP",
"port": 3306
}
}
```
```json
{
"healthCheck": {
"type": "TCP",
"port": "database"
}
}
```
```json
{
"healthCheck": {
"type": "HTTP",
"port": "web",
"http": {
"path": "/healthz"
}
}
}
```

feat(schema): Add healthCheck field

---

schema/prebuilt.json

fix(schema): Reduce the complexity of port in health check

---

schema/index.html
schema/upload-api/index.html
schema/upload-api/openapi.json

feat(schema): Add upload API v2 schema

---

docs/devenv.lock
docs/pages/en-US/developer/_meta.ts
docs/pages/en-US/developer/public-api.mdx
docs/pages/en-US/developer/use-api-key.mdx
docs/pages/es-ES/developer/_meta.ts
docs/pages/es-ES/developer/public-api.mdx
docs/pages/es-ES/developer/use-api-key.mdx
docs/pages/ja-JP/developer/_meta.ts
docs/pages/ja-JP/developer/public-api.mdx
docs/pages/ja-JP/developer/use-api-key.mdx
docs/pages/zh-CN/developer/_meta.ts
docs/pages/zh-CN/developer/public-api.mdx
docs/pages/zh-CN/developer/use-api-key.mdx
docs/pages/zh-TW/developer/_meta.ts
docs/pages/zh-TW/developer/public-api.mdx
docs/pages/zh-TW/developer/use-api-key.mdx

- **chore: update devenv lock [skip ci]**
- **docs(developer): rewrite Public API docs**
- **docs(developer): translate Public API docs to zh-CN**
- **docs(developer): translate Public API docs to ja-JP**
- **docs(developer): translate Public API docs to en-US**
- **docs(developer): translate Public API docs to es-ES**

ZEA-5137: update public API docs

---

schema/index.html
schema/prebuilt.json
schema/template.json

- **chore: update schema repository style**
- **refactor: simplify schema structure**

ZEA-5298: Simplify schema structure
