zeabur/zeabur

- pages/get-started.en-US.mdx
- pages/get-started.zh-CN.mdx
- pages/get-started.zh-TW.mdx
fix: update `environment variables` link of `get-start` page.
[preview](https://zeabur-docs-preview.zeabur.app/zh-TW/get-started#%E4%B8%8B%E4%B8%80%E6%AD%A5)
> fix: update get-start page link.

- pages/guides/nodejs/express.en-US.mdx
- pages/guides/nodejs/express.zh-CN.mdx
- pages/guides/nodejs/express.zh-TW.mdx
修正了文档中的错误。
`npm install -g` 之后，`express-generator` 直接就在 PATH 下，可以直接运行 `express-generator` 进行 express 项目创建。
`npx express-genetor` 则是先下载再执行，无需将 `express-generator` 全局安装。
因此这两个命令选一个就行，但是这里两个全都加上了，也没有其他提示，感觉会误导人。
express 那边现在推荐使用 `npx`，所以我删掉了 `npm install -g` 这个方式。
> docs: update express

- docs/theme.config.js
- Fix base URL to `https://github.com/zeabur/zeabur/tree/main/docs`
> fix: repo base url for sidebar edit this page

- marketplace/ghost.json
`ghost` actually picks the `url` environment variable; therefore, we should not set a value that is registerable to prevent the potential malicious attack.
> fix(marketplace/ghost): Safe placeholder

- marketplace/halo.json
Bump Halo version to 2.6.
https://github.com/halo-dev/halo/releases/tag/v2.6.0
> chore: bump halo version to 2.6

- marketplace/umami-mysql.json
https://github.com/zeabur/zeabur/blob/main/marketplace/umami.json#L7
看起來原本 umami 是用 postgres 的 image，這會導致若用 mysql 為數據庫的話會 connect 不到
這邊新增 mysql 版本的 image
ref: https://github.com/umami-software/umami/pkgs/container/umami/114983885?tag=mysql-latest
> fix(marketplace): add mysql support to umami

- docs/pages/databases/postgresql.en-US.mdx
- docs/pages/databases/postgresql.zh-CN.mdx
- docs/pages/databases/postgresql.zh-TW.mdx
In the document variable's prefix is `POSTGRESQL_`, but in fact variable's prefix is `POSTGRES`:
> fix: fix postgres environment variable

- marketplace/halo.json
- prebuilts/halo.toml
Bump Halo version to 2.10
https://github.com/halo-dev/halo/releases/tag/v2.10.0
> chore: bump halo version to 2.10

- prebuilts/mongodb.toml
ref: https://github.com/docker-library/mongo/blob/862e9ee0ed0297367b13529a6712be7ed180f753/7.0/docker-entrypoint.sh#L10-L23
> fix: MongoDB prebuilt failed to start caused by dir permission

- prebuilts/mongodb.toml
- ci: Check if prebuilt definition matches schema
- fix(prebuilts/mongodb): Use mongosh to connect to the database
> ZEA-1980: Prebuilt's Mongo Connection Command calls mongosh

- docs/pages/advanced/builds.zh-CN.mdx
Change zbapck to zbpack.
The second zbpack link in the document is mistyped as https://github.com/zeabur/zbapck, and should be the correct URL https://github.com/zeabur/zbpack aligned with the above.
> docs(builds/zh-CN): "zbpack" typo in URL

- docs/pages/databases/rabbitmq.en-US.mdx
- docs/pages/databases/rabbitmq.zh-CN.mdx
- docs/pages/databases/rabbitmq.zh-TW.mdx
- prebuilts/rabbitmq.toml
- create `docs/pages/databases/rabbitmq.en-US.mdx`
- create `docs/pages/databases/rabbitmq.zh-CN.mdx`
- create `docs/pages/databases/rabbitmq.zh-TW.mdx`
- update `prebuilts/rabbitmq.toml`
```
Management Plugin
There is a second set of tags provided with the [management plugin](https://www.rabbitmq.com/management.html) installed and enabled by default, which is available on the standard management port of 15672, with the default username and password of guest / guest:
$ docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3-management
You can access it by visiting http://container-ip:15672 in a browser or, if you need access outside the host, on port 8080:
$ docker run -d --hostname my-rabbit --name some-rabbit -p 8080:15672 rabbitmq:3-management
You can then go to …
```
> feat(docs/rabbitmq.toml) RabbitMq Docs/ Web

- docs/pages/guides/nodejs.en-US.mdx
> docs: fix typo in nodejs guide

- prebuilts/featbit-data-analytics-server.toml
`MONGO_URI` and `MONGO_HOST` been implicitly injected into services.
https://github.com/zeabur/zeabur/blob/main/prebuilts/mongodb.toml
> refactor: remove unused environment variables

- prebuilts/linkwarden.toml
Linkwarden is a collaborative bookmark manager to collect, organize and archive webpages.
Solves #381 
References: https://hub.docker.com/layers/saifbenali/linkwarden/v2.5.1/images/sha256-1aa951c23bca24c16b536c79ac522c5dad05b6bb6f9a08cabc7327b3bb3db8c2?context=explore
> prebuilt: add linkwarden

- prebuilts/halo.toml
Bump Halo version to 2.14
- https://github.com/halo-dev/halo/releases/tag/v2.14.0
- https://github.com/halo-dev/halo/releases/tag/v2.13.0
- https://github.com/halo-dev/halo/releases/tag/v2.12.0
- https://github.com/halo-dev/halo/releases/tag/v2.11.0
> chore(prebuilt): bump halo version to 2.14

- prebuilts/supabase-db.toml
${PASSWORD} is the unique random password generated for each service.
The "JWT_SECRET" has been changed to a relatively-safe password, and I add the "required" flag, indicating the user should change it manually.
> refactor(prebuilts/supabase): Update default password

- prebuilts/directus.toml
This PR updates the default values for the following environment variables to make it easier for users to get started with Directus:
- `DB_XXX` is alternative by `DB_CONNECTION_STRING`.
- `REDIS` is now `REDIS_URI`.
The previous value for `REDIS` did not include a username or password, which caused authorization to fail. This PR updates the default value to include a username and password, so that users can get started with Redis without having to manually configure it.
> fix(prebuilts): use correct envs for database and redis

- prebuilts/directus.toml
This PR add some admin information to instruction sections:
- Admin Email
- Admin Password
> feat(prebuilts): add directus admin info to instruction sections

- docs/pages/guides/dart/flutter.en-US.mdx
- docs/pages/guides/dart/flutter.ja-JP.mdx
- docs/pages/guides/dart/flutter.zh-CN.mdx
- docs/pages/guides/dart/flutter.zh-TW.mdx
- docs/pages/guides/nodejs/astro.en-US.mdx
- docs/pages/guides/nodejs/astro.ja-JP.mdx
- docs/pages/guides/nodejs/astro.zh-CN.mdx
- docs/pages/guides/nodejs/astro.zh-TW.mdx
- docs/pages/guides/nodejs/svelte-kit.en-US.mdx
- docs/pages/guides/nodejs/svelte-kit.zh-TW.mdx
In the docs for Astro, Flutter, and Sveltekit, the "Deploy in CLI" links redirect to an error page due to faulty link. This pull request seeks to replace it with the correct link.
> fix: Deploy CLI link errors

- prebuilts/rss3-node.toml
State that this is an Alpha Node.
Beta Node will be released soon, so this avoids the confusion.
Also in the future, Alpha Node will be deprecated.
> chore: update rss3-node.toml

- .github/workflows/check-prebuilts.yml
It currently introduces too many fake positives.
I will refactor it in a better way later.
> chore: Disable reference lint

- templates/.vscode/settings.json
- templates/kafka/README.md
- templates/kafka/template.yaml
[![Deploy with Zeabur](https://zeabur.com/button.svg)](https://zeabur.com/templates/ZBC4S7)
[Apache Kafka](https://kafka.apache.org) is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications.
Note that for _external_ connections to the broker i.e. those from _outside_ the docker network. This could be from the host machine running docker, or maybe further afield if you've got a more complicated setup.
If the latter is true, you will need to change the value `localhost` in `KAFKA_ADVERTISED_LISTENERS` to the forwarded hostname and port, which you can see in the "Networking" tab.
For connections _internal_ to the docker network, such as from other …
> feat(templates): Add Kafka template

- docs/sitemap.js
Update sitemap script for Nextra v3, current sitemap script is not working for the Nextra v3 URL.
> fix(docs): Update sitemap script for Nextra v3
